title: Walter Teitelbaum
description: Welcome to my site. Feel free to have a look around.
url: "https://walter.teitelbaum.us/"
baseurl: ""

theme: cvless

destination: docs

# site settings
taglong: Welcome to my site.
tagshort: Engineer
cv: true

# author settings
author:
  name: Walter Teitelbaum
  email: walter@teitelbaum.us
photo: assets/files/walt_portrait.jpeg
address: Seattle, WA
phone: +1 510 365 7859

# profile links
profile:
  facebook: https://www.facebook.com/walter.teitelbaum/
  instagram: https://www.instagram.com/walter.teitelbaum/
  linkedin: https://www.linkedin.com/in/walter-teitelbaum/
  github: https://github.com/jewbee2000

# build settings
permalink: pretty
exclude:
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never